# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := oscontext ospthread

.PHONY: all clean help compiletests benchs preempt $(PROJECTS)

all: $(PROJECTS)

oscontext: 
	@echo "==== Building oscontext ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f oscontext.make

ospthread: 
	@echo "==== Building ospthread ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f ospthread.make

clean:
	@${MAKE} --no-print-directory -C build -f oscontext.make clean
	@${MAKE} --no-print-directory -C build -f ospthread.make clean

compiletests: oscontext ospthread
	./tests/test.sh $(config)

benchs: compiletests
	./benchs/bench.sh

preempt:
	LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$(pwd)/build" ./tests/build/03-preempt-context 2>/dev/null

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   oscontext"
	@echo "   ospthread"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
